// frontend/src/components/schedules/schedule-editor.tsx
'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Save, X, HelpCircle, Clock } from 'lucide-react';
import { apiService } from '@/services/api';
import { toast } from 'sonner';

interface Schedule {
  id: string;
  name: string;
  timezone: string;
  cron_expression: string;
  badge_types: string[];
  reprocess_all: boolean;
  enabled: boolean;
  target_libraries: string[];
  created_at: string;
  updated_at: string;
}

interface Library {
  id: string;
  name: string;
  type: string;
}

interface ScheduleEditorProps {
  editingSchedule?: Schedule | null;
  onSave: () => void;
  onCancel: () => void;
}

const TIMEZONES = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Toronto',
  'Europe/London',
  'Europe/Berlin',
  'Asia/Tokyo',
  'Australia/Sydney',
];

const CRON_PRESETS = {
  hourly: { label: 'Every Hour', cron: '0 * * * *' },
  daily_2am: { label: 'Daily at 2:00 AM', cron: '0 2 * * *' },
  weekly: { label: 'Weekly (Sunday 2:00 AM)', cron: '0 2 * * 0' },
  monthly: { label: 'Monthly (1st day 2:00 AM)', cron: '0 2 1 * *' },
  every_6_hours: { label: 'Every 6 Hours', cron: '0 */6 * * *' },
  weekdays_2am: { label: 'Weekdays at 2:00 AM', cron: '0 2 * * 1-5' },
  weekends_2am: { label: 'Weekends at 2:00 AM', cron: '0 2 * * 6,0' },
  twice_daily: { label: 'Twice Daily (2:00 AM & 2:00 PM)', cron: '0 2,14 * * *' },
};

export function ScheduleEditor({ editingSchedule, onSave, onCancel }: ScheduleEditorProps) {
  const [formData, setFormData] = useState({
    name: '',
    timezone: 'UTC',
    cron_expression: '0 2 * * *',
    badge_types: [] as string[],
    reprocess_all: false,
    enabled: true,
    target_libraries: [] as string[],
  });

  const [availableBadgeTypes, setAvailableBadgeTypes] = useState<string[]>([]);
  const [availableLibraries, setAvailableLibraries] = useState<Library[]>([]);
  const [selectedPreset, setSelectedPreset] = useState<string>('custom');
  const [loading, setLoading] = useState(false);
  const [showCronHelp, setShowCronHelp] = useState(false);

  // Load initial data
  useEffect(() => {
    const loadData = async () => {
      try {
        console.log('🔍 Loading schedule editor data...');
        
        // Load badge types
        const badgeTypesResponse = await apiService.getScheduleBadgeTypes();
        console.log('📊 Badge types response:', badgeTypesResponse);
        const badgeTypes = badgeTypesResponse?.badge_types || [];
        setAvailableBadgeTypes(badgeTypes);
        console.log('✅ Badge types loaded:', badgeTypes);
        
        // Load libraries (handle errors gracefully)
        try {
          const librariesResponse = await apiService.getScheduleLibraries();
          console.log('📊 Libraries response:', librariesResponse);
          const libraries = librariesResponse?.libraries || [];
          setAvailableLibraries(libraries);
          console.log('✅ Libraries loaded:', libraries);
        } catch (libraryError) {
          console.warn('⚠️ Failed to load libraries:', libraryError);
          // Don't show error toast for libraries - they might fail if Jellyfin isn't configured
          setAvailableLibraries([]);
        }
        
      } catch (error) {
        console.error('❌ Failed to load editor data:', error);
        toast.error('Failed to load configuration data');
      }
    };
    
    loadData();
  }, []);

  // Set form data when editing
  useEffect(() => {
    if (editingSchedule) {
      setFormData({
        name: editingSchedule.name,
        timezone: editingSchedule.timezone,
        cron_expression: editingSchedule.cron_expression,
        badge_types: editingSchedule.badge_types,
        reprocess_all: editingSchedule.reprocess_all,
        enabled: editingSchedule.enabled,
        target_libraries: editingSchedule.target_libraries,
      });
      
      // Try to match preset
      const matchingPreset = Object.entries(CRON_PRESETS).find(
        ([_, preset]) => preset.cron === editingSchedule.cron_expression
      );
      setSelectedPreset(matchingPreset ? matchingPreset[0] : 'custom');
    }
  }, [editingSchedule]);

  const handlePresetChange = (preset: string) => {
    setSelectedPreset(preset);
    if (preset !== 'custom' && CRON_PRESETS[preset as keyof typeof CRON_PRESETS]) {
      setFormData(prev => ({
        ...prev,
        cron_expression: CRON_PRESETS[preset as keyof typeof CRON_PRESETS].cron
      }));
    }
  };

  const handleBadgeTypeToggle = (badgeType: string) => {
    setFormData(prev => ({
      ...prev,
      badge_types: prev.badge_types.includes(badgeType)
        ? prev.badge_types.filter(type => type !== badgeType)
        : [...prev.badge_types, badgeType]
    }));
  };

  const handleLibraryToggle = (libraryId: string) => {
    setFormData(prev => ({
      ...prev,
      target_libraries: prev.target_libraries.includes(libraryId)
        ? prev.target_libraries.filter(id => id !== libraryId)
        : [...prev.target_libraries, libraryId]
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name.trim()) {
      toast.error('Schedule name is required');
      return;
    }
    
    if (!formData.cron_expression.trim()) {
      toast.error('Cron expression is required');
      return;
    }

    try {
      setLoading(true);
      
      if (editingSchedule) {
        await apiService.updateSchedule(editingSchedule.id, formData);
        toast.success('Schedule updated successfully');
      } else {
        await apiService.createSchedule(formData);
        toast.success('Schedule created successfully');
      }
      
      onSave();
    } catch (error) {
      console.error('Failed to save schedule:', error);
      toast.error('Failed to save schedule');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-semibold">
          {editingSchedule ? 'Edit Schedule' : 'Create New Schedule'}
        </h2>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={onCancel}>
            <X className="h-4 w-4 mr-2" />
            Cancel
          </Button>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Basic Information</CardTitle>
            <CardDescription>
              Configure the schedule name and timing
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Schedule Name</Label>
              <Input
                id="name"
                placeholder="Enter schedule name"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="timezone">Timezone</Label>
              <Select value={formData.timezone} onValueChange={(value) => setFormData(prev => ({ ...prev, timezone: value }))}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {TIMEZONES.map((tz) => (
                    <SelectItem key={tz} value={tz}>{tz}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Quick Presets</Label>
              <Select value={selectedPreset} onValueChange={handlePresetChange}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="custom">Custom Expression</SelectItem>
                  {Object.entries(CRON_PRESETS).map(([key, preset]) => (
                    <SelectItem key={key} value={key}>{preset.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Label htmlFor="cron">Cron Expression</Label>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowCronHelp(!showCronHelp)}
                >
                  <HelpCircle className="h-4 w-4" />
                </Button>
              </div>
              <Input
                id="cron"
                placeholder="0 2 * * *"
                value={formData.cron_expression}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, cron_expression: e.target.value }));
                  setSelectedPreset('custom');
                }}
                required
              />
              {showCronHelp && (
                <div className="p-3 bg-muted rounded text-sm">
                  <p className="font-medium mb-2">Cron Expression Format:</p>
                  <p className="font-mono">minute hour day month weekday</p>
                  <div className="mt-2 space-y-1">
                    <p>• <code>0 2 * * *</code> - Daily at 2:00 AM</p>
                    <p>• <code>0 */6 * * *</code> - Every 6 hours</p>
                    <p>• <code>0 2 * * 1-5</code> - Weekdays at 2:00 AM</p>
                    <p>• <code>0 2 1 * *</code> - Monthly on 1st day at 2:00 AM</p>
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center space-x-2">
              <Switch
                id="enabled"
                checked={formData.enabled}
                onCheckedChange={(checked) => setFormData(prev => ({ ...prev, enabled: checked }))}
              />
              <Label htmlFor="enabled">Enable Schedule</Label>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Processing Options</CardTitle>
            <CardDescription>
              Configure what will be processed when the schedule runs
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <Label>Badge Types to Apply</Label>
              {availableBadgeTypes.length === 0 ? (
                <div className="text-center py-4">
                  <Clock className="h-8 w-8 mx-auto mb-2 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Loading badge types...</p>
                </div>
              ) : (
                <>
                  <div className="grid grid-cols-2 gap-2">
                    {availableBadgeTypes.map((badgeType) => (
                      <div key={badgeType} className="flex items-center space-x-2">
                        <Checkbox
                          id={`badge-${badgeType}`}
                          checked={formData.badge_types.includes(badgeType)}
                          onCheckedChange={() => handleBadgeTypeToggle(badgeType)}
                        />
                        <Label htmlFor={`badge-${badgeType}`} className="capitalize">
                          {badgeType}
                        </Label>
                      </div>
                    ))}
                  </div>
                  {formData.badge_types.length === 0 && (
                    <p className="text-sm text-muted-foreground">
                      No badge types selected. Schedule will not process any items.
                    </p>
                  )}
                </>
              )}
            </div>

            <Separator />

            <div className="flex items-center space-x-2">
              <Switch
                id="reprocess_all"
                checked={formData.reprocess_all}
                onCheckedChange={(checked) => setFormData(prev => ({ ...prev, reprocess_all: checked }))}
              />
              <div className="space-y-1">
                <Label htmlFor="reprocess_all">Reprocess All Items</Label>
                <p className="text-sm text-muted-foreground">
                  When enabled, processes all items regardless of existing 'aphrodite-overlay' metadata
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Target Libraries</CardTitle>
            <CardDescription>
              Select which Jellyfin libraries to process (leave all unchecked to process all libraries)
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {availableLibraries.length === 0 ? (
                <div className="text-center py-4">
                  <Clock className="h-8 w-8 mx-auto mb-2 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Loading libraries...</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    If this persists, check that Jellyfin is configured and running
                  </p>
                </div>
              ) : (
                <div className="space-y-2">
                  {availableLibraries.map((library) => (
                    <div key={library.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={`library-${library.id}`}
                        checked={formData.target_libraries.includes(library.id)}
                        onCheckedChange={() => handleLibraryToggle(library.id)}
                      />
                      <Label htmlFor={`library-${library.id}`} className="flex items-center gap-2">
                        {library.name}
                        <Badge variant="outline" className="text-xs">
                          {library.type}
                        </Badge>
                      </Label>
                    </div>
                  ))}
                </div>
              )}
              {formData.target_libraries.length === 0 && availableLibraries.length > 0 && (
                <p className="text-sm text-muted-foreground mt-2">
                  No libraries selected. Schedule will process all movie and TV show libraries.
                </p>
              )}
            </div>
          </CardContent>
        </Card>

        <div className="flex justify-end gap-2">
          <Button type="button" variant="outline" onClick={onCancel}>
            Cancel
          </Button>
          <Button type="submit" disabled={loading}>
            {loading ? (
              <>
                <Clock className="h-4 w-4 mr-2 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <Save className="h-4 w-4 mr-2" />
                {editingSchedule ? 'Update Schedule' : 'Create Schedule'}
              </>
            )}
          </Button>
        </div>
      </form>
    </div>
  );
}

// aphrodite-web/frontend/src/components/ScheduleEditor.vue
<template>
  <div class="schedule-editor">
    <div class="card bg-base-100 shadow-lg">
      <div class="card-body">
        <h2 class="card-title mb-4">
          {{ isEditing ? 'Edit Schedule' : 'Create New Schedule' }}
        </h2>
        
        <form @submit.prevent="saveSchedule" class="space-y-6">
          <!-- Basic Information -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="form-control">
              <label class="label">
                <span class="label-text font-medium">Schedule Name</span>
                <span class="label-text-alt text-error">*</span>
              </label>
              <input
                v-model="schedule.name"
                type="text"
                placeholder="e.g., Nightly Full Processing"
                class="input input-bordered"
                :class="{ 'input-error': errors.name }"
                required
              />
              <label v-if="errors.name" class="label">
                <span class="label-text-alt text-error">{{ errors.name }}</span>
              </label>
            </div>
            
            <div class="form-control">
              <label class="label">
                <span class="label-text font-medium">Timezone</span>
              </label>
              <select v-model="schedule.timezone" class="select select-bordered">
                <option value="UTC">UTC</option>
                <option value="America/New_York">Eastern Time</option>
                <option value="America/Chicago">Central Time</option>
                <option value="America/Denver">Mountain Time</option>
                <option value="America/Los_Angeles">Pacific Time</option>
                <option value="America/Toronto">Toronto</option>
                <option value="Europe/London">London</option>
                <option value="Europe/Paris">Paris</option>
                <option value="Asia/Tokyo">Tokyo</option>
              </select>
            </div>
          </div>
          
          <!-- Schedule Settings -->
          <div class="divider">Schedule</div>
          
          <CronBuilder 
            v-model="schedule.cron" 
            @valid="cronValid = $event"
          />
          
          <!-- Processing Options -->
          <div class="divider">Processing Options</div>
          
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Badge Types -->
            <div class="form-control">
              <label class="label">
                <span class="label-text font-medium">Badge Types</span>
              </label>
              <div class="space-y-2">
                <div class="form-control">
                  <label class="cursor-pointer label justify-start gap-2">
                    <input 
                      v-model="schedule.processing_options.audio_badges" 
                      type="checkbox" 
                      class="checkbox checkbox-primary"
                    />
                    <span class="label-text">Audio Badges</span>
                  </label>
                </div>
                <div class="form-control">
                  <label class="cursor-pointer label justify-start gap-2">
                    <input 
                      v-model="schedule.processing_options.resolution_badges" 
                      type="checkbox" 
                      class="checkbox checkbox-primary"
                    />
                    <span class="label-text">Resolution Badges</span>
                  </label>
                </div>
                <div class="form-control">
                  <label class="cursor-pointer label justify-start gap-2">
                    <input 
                      v-model="schedule.processing_options.review_badges" 
                      type="checkbox" 
                      class="checkbox checkbox-primary"
                    />
                    <span class="label-text">Review Badges</span>
                  </label>
                </div>
              </div>
            </div>
            
            <!-- Additional Options -->
            <div class="form-control">
              <label class="label">
                <span class="label-text font-medium">Additional Options</span>
              </label>
              <div class="space-y-2">
                <div class="form-control">
                  <label class="cursor-pointer label justify-start gap-2">
                    <input 
                      v-model="schedule.processing_options.force_refresh" 
                      type="checkbox" 
                      class="checkbox checkbox-secondary"
                    />
                    <span class="label-text">Force Refresh</span>
                  </label>
                  <div class="text-xs opacity-60 ml-6 -mt-1">
                    Re-process all items, even if already processed. Use when updating badge settings or fixing errors.
                  </div>
                </div>
                <div class="form-control">
                  <label class="cursor-pointer label justify-start gap-2">
                    <input 
                      v-model="schedule.enabled" 
                      type="checkbox" 
                      class="checkbox checkbox-accent"
                    />
                    <span class="label-text">Enable Schedule</span>
                  </label>
                  <div class="text-xs opacity-60 ml-6 -mt-1">
                    When enabled, schedule runs automatically. When disabled, schedule is saved but won't run automatically.
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Target Directories -->
          <div class="form-control">
            <label class="label">
              <span class="label-text font-medium">Target Directories</span>
            </label>
            
            <!-- Jellyfin Libraries Section -->
            <div v-if="jellyfinLibraries.length > 0" class="mb-4">
              <div class="flex items-center justify-between mb-2">
                <span class="text-sm font-medium">Jellyfin Libraries</span>
                <button
                  type="button"
                  @click="refreshJellyfinLibraries"
                  class="btn btn-ghost btn-xs"
                  :disabled="loadingLibraries"
                >
                  <span v-if="loadingLibraries" class="loading loading-spinner loading-xs"></span>
                  <span v-else>↻</span>
                  Refresh
                </button>
              </div>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div 
                  v-for="library in jellyfinLibraries" 
                  :key="library.id"
                  class="form-control"
                >
                  <label class="cursor-pointer label justify-start gap-2 py-1">
                    <input 
                      type="checkbox"
                      class="checkbox checkbox-sm checkbox-primary"
                      :checked="isLibrarySelected(library)"
                      @change="toggleLibrary(library, $event.target.checked)"
                    />
                    <div class="flex flex-col">
                      <span class="label-text text-sm">{{ library.name }}</span>
                      <span v-if="library.type" class="label-text-alt text-xs opacity-60">
                        {{ library.type }}
                      </span>
                    </div>
                  </label>
                </div>
              </div>
              <div class="divider divider-horizontal text-xs opacity-50">OR</div>
            </div>
            
            <!-- Manual Directory Entry -->
            <div class="mb-2">
              <span class="text-sm font-medium">Manual Entry</span>
            </div>
            <div class="flex flex-wrap gap-2 mb-2">
              <div 
                v-for="(dir, index) in schedule.processing_options.target_directories" 
                :key="index"
                class="badge gap-2"
                :class="getDirectoryBadgeClass(dir)"
              >
                {{ dir }}
                <button 
                  type="button"
                  @click="removeDirectory(index)"
                  class="btn btn-ghost btn-xs"
                >
                  ×
                </button>
              </div>
            </div>
            <div class="input-group">
              <input
                v-model="newDirectory"
                type="text"
                placeholder="e.g., movies, tv, anime"
                class="input input-bordered flex-1"
                @keyup.enter="addDirectory"
              />
              <button 
                type="button"
                @click="addDirectory"
                class="btn btn-primary"
                :disabled="!newDirectory.trim()"
              >
                Add
              </button>
            </div>
            <label class="label">
              <span class="label-text-alt">
                Select from Jellyfin libraries above or manually add directory names
              </span>
            </label>
          </div>
          
          <!-- Actions -->
          <div class="card-actions justify-end gap-2 pt-4">
            <button 
              type="button" 
              @click="$emit('cancel')"
              class="btn btn-ghost"
            >
              Cancel
            </button>
            <button 
              type="submit" 
              class="btn btn-primary"
              :disabled="!isFormValid || loading"
            >
              <span v-if="loading" class="loading loading-spinner loading-sm"></span>
              {{ isEditing ? 'Update Schedule' : 'Create Schedule' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed, watch, onMounted } from 'vue'
import CronBuilder from './CronBuilder.vue'
import api from '@/api'

export default {
  name: 'ScheduleEditor',
  components: {
    CronBuilder
  },
  props: {
    editSchedule: {
      type: Object,
      default: null
    }
  },
  emits: ['save', 'cancel'],
  setup(props, { emit }) {
    const loading = ref(false)
    const cronValid = ref(false)
    const newDirectory = ref('')
    const errors = ref({})
    const jellyfinLibraries = ref([])
    const loadingLibraries = ref(false)
    
    // Default schedule structure
    const defaultSchedule = {
      name: '',
      cron: '0 2 * * *',
      timezone: 'UTC',
      enabled: true,
      processing_options: {
        audio_badges: true,
        resolution_badges: true,
        review_badges: true,
        force_refresh: false,
        target_directories: ['movies', 'tv']
      }
    }
    
    const schedule = ref({ ...defaultSchedule })
    
    // Check if editing existing schedule
    const isEditing = computed(() => !!props.editSchedule)
    
    // Form validation
    const isFormValid = computed(() => {
      return schedule.value.name.trim() && 
             schedule.value.cron.trim() && 
             cronValid.value &&
             (schedule.value.processing_options.audio_badges ||
              schedule.value.processing_options.resolution_badges ||
              schedule.value.processing_options.review_badges)
    })
    
    // Watch for editSchedule prop changes
    watch(() => props.editSchedule, (newSchedule) => {
      if (newSchedule) {
        schedule.value = { ...newSchedule }
      } else {
        schedule.value = { ...defaultSchedule }
      }
      errors.value = {}
    }, { immediate: true })
    
    const addDirectory = () => {
      const dir = newDirectory.value.trim()
      if (dir && !schedule.value.processing_options.target_directories.includes(dir)) {
        schedule.value.processing_options.target_directories.push(dir)
        newDirectory.value = ''
      }
    }
    
    const removeDirectory = (index) => {
      schedule.value.processing_options.target_directories.splice(index, 1)
    }
    
    const validateForm = () => {
      errors.value = {}
      
      if (!schedule.value.name.trim()) {
        errors.value.name = 'Schedule name is required'
      }
      
      if (!schedule.value.cron.trim()) {
        errors.value.cron = 'Cron expression is required'
      }
      
      if (!cronValid.value) {
        errors.value.cron = 'Invalid cron expression'
      }
      
      if (!schedule.value.processing_options.audio_badges &&
          !schedule.value.processing_options.resolution_badges &&
          !schedule.value.processing_options.review_badges) {
        errors.value.badges = 'At least one badge type must be selected'
      }
      
      return Object.keys(errors.value).length === 0
    }
    
    const saveSchedule = async () => {
      if (!validateForm()) {
        return
      }
      
      loading.value = true
      
      try {
        const scheduleData = { ...schedule.value }
        
        if (isEditing.value) {
          await api.schedules.updateSchedule(scheduleData.id, scheduleData)
        } else {
          await api.schedules.createSchedule(scheduleData)
        }
        
        emit('save', scheduleData)
      } catch (error) {
        console.error('Error saving schedule:', error)
        // Handle error - maybe show a toast notification
      } finally {
        loading.value = false
      }
    }
    
    // Jellyfin library management
    const fetchJellyfinLibraries = async () => {
      loadingLibraries.value = true
      try {
        const response = await api.schedules.getJellyfinLibraries()
        jellyfinLibraries.value = response.data.libraries || []
      } catch (error) {
        console.error('Error fetching Jellyfin libraries:', error)
        jellyfinLibraries.value = []
      } finally {
        loadingLibraries.value = false
      }
    }
    
    const refreshJellyfinLibraries = () => {
      fetchJellyfinLibraries()
    }
    
    const isLibrarySelected = (library) => {
      return schedule.value.processing_options.target_directories.includes(library.name)
    }
    
    const toggleLibrary = (library, isChecked) => {
      const directories = schedule.value.processing_options.target_directories
      const libraryName = library.name
      
      if (isChecked && !directories.includes(libraryName)) {
        directories.push(libraryName)
      } else if (!isChecked && directories.includes(libraryName)) {
        const index = directories.indexOf(libraryName)
        directories.splice(index, 1)
      }
    }
    
    const getDirectoryBadgeClass = (directory) => {
      // Check if this directory matches a Jellyfin library
      const isJellyfinLibrary = jellyfinLibraries.value.some(lib => lib.name === directory)
      return isJellyfinLibrary ? 'badge-primary' : 'badge-secondary'
    }
    
    // Load Jellyfin libraries on component mount
    onMounted(() => {
      fetchJellyfinLibraries()
    })
    
    return {
      schedule,
      loading,
      cronValid,
      newDirectory,
      errors,
      isEditing,
      isFormValid,
      addDirectory,
      removeDirectory,
      saveSchedule,
      jellyfinLibraries,
      loadingLibraries,
      refreshJellyfinLibraries,
      isLibrarySelected,
      toggleLibrary,
      getDirectoryBadgeClass
    }
  }
}
</script>
